//
// This is a list of all the beasts available for summoning.
//

import 'beast_model.dart';

const kBeasts = const <Beast>[
  const Beast(
    bType: 'Boar',
    cr: '1/4',
    count: 8,
    info: 'M  AC:11  Str:1  Dex:0  Con:1  Int:-4  Wis:-1  Cha:-3  R:40',
    hitDiceCt: 2,
    hitDiceSize: 8,
    hitDiceBonus: 2,
    attack1: 'Tusk',
    attBonus1: 3,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 1,
    attack2: 'Charge',
    attBonus2: 3,
    damDiceCt2: 2,
    damDiceSize2: 6,
    damBonus2: 1
  ),
  const Beast(
    bType: 'Constrictor Snake',
    cr: '1/4',
    count: 8,
    info: 'L  AC:12  Str:2  Dex:2  Con:1  Int:-5  Wis:0  Cha:-4  R:30 S:30',
    hitDiceCt: 2,
    hitDiceSize: 10,
    hitDiceBonus: 2,
    attack1: 'Bite',
    attBonus1: 4,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 2,
    attack2: 'Constrict',
    attBonus2: 4,
    damDiceCt2: 1,
    damDiceSize2: 8,
    damBonus2: 2
  ),
  const Beast(
    bType: 'Flying Snake',
    cr: '1/8',
    count: 8,
    info: 'T  AC:14  Str:-3  Dex:4  Con:0  Int:-4  Wis:1  Cha:-3  R:30 F:60 S:30',
    hitDiceCt: 2,
    hitDiceSize: 4,
    hitDiceBonus: 0,
    attack1: 'Bite',
    attBonus1: 6,
    damDiceCt1: 3,
    damDiceSize1: 4,
    damBonus1: 1
  ),
  const Beast(
    bType: 'Elk',
    cr: '1/4',
    count: 8,
    info: 'L  AC:10  Str:3  Dex:0  Con:1  Int:-4  Wis:0  Cha:-2  R:50',
    hitDiceCt: 2,
    hitDiceSize: 10,
    hitDiceBonus: 2,
    attack1: 'Ram',
    attBonus1: 5,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 3,
    attack2: 'Hooves',
    attBonus2: 5,
    damDiceCt2: 2,
    damDiceSize2: 4,
    damBonus2: 3
  ),
  const Beast(
    bType: 'Giant Badger',
    cr: '1/4',
    count: 8,
    info: 'M  AC:10  Str:1  Dex:0  Con:2  Int:-4  Wis:1  Cha:-3  R:30 B:10',
    hitDiceCt: 2,
    hitDiceSize: 8,
    hitDiceBonus: 4,
    attack1: 'Bite',
    attBonus1: 3,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 1,
    attack2: 'Claws',
    attBonus2: 3,
    damDiceCt2: 2,
    damDiceSize2: 4,
    damBonus2: 1
  ),
  const Beast(
    bType: 'Giant Bat',
    cr: '1/4',
    count: 8,
    info: 'L  AC:13  Str:2  Dex:3  Con:0  Int:-4  Wis:1  Cha:-2  R:10 F:60',
    hitDiceCt: 4,
    hitDiceSize: 10,
    hitDiceBonus: 0,
    attack1: 'Bite',
    attBonus1: 4,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 2
  ),
  const Beast(
    bType: 'Giant Owl',
    cr: '1/4',
    count: 8,
    info: 'L  AC:12  Str:1  Dex:2  Con:1  Int:-1  Wis:1  Cha:0  R:5 F:60',
    hitDiceCt: 3,
    hitDiceSize: 10,
    hitDiceBonus: 3,
    attack1: 'Talons',
    attBonus1: 3,
    damDiceCt1: 2,
    damDiceSize1: 6,
    damBonus1: 1
  ),
  const Beast(
    bType: 'Giant Poisonous Snake',
    cr: '1/4',
    count: 8,
    info: 'M  AC:14  Str:0  Dex:4  Con:1  Int:-4  Wis:0  Cha:-4  R:30 S:30',
    hitDiceCt: 2,
    hitDiceSize: 8,
    hitDiceBonus: 2,
    attack1: 'Bite',
    attBonus1: 6,
    damDiceCt1: 1,
    damDiceSize1: 4,
    damBonus1: 1,
    attack2: 'Bite Poison',
    damDiceCt2: 3,
    damDiceSize2: 6,
    damBonus2: 0
  ),
  const Beast(
      bType: 'Giant Wolf Spider',
      cr: '1/4',
      count: 8,
      info: 'M  AC:13  Str:1  Dex:3  Con:1  Int:-4  Wis:1  Cha:-3  R:40 C:40',
      hitDiceCt: 2,
      hitDiceSize: 8,
      hitDiceBonus: 2,
      attack1: 'Bite',
      attBonus1: 3,
      damDiceCt1: 1,
      damDiceSize1: 6,
      damBonus1: 1,
  ),
  const Beast(
      bType: 'Panther',
      cr: '1/4',
      count: 8,
      info: 'M  AC:12  Str:2  Dex:2  Con:0  Int:-4  Wis:2  Cha:-2  R:50 C:40',
      hitDiceCt: 3,
      hitDiceSize: 8,
      hitDiceBonus: 0,
      attack1: 'Claw',
      attBonus1: 4,
      damDiceCt1: 1,
      damDiceSize1: 4,
      damBonus1: 2,
      attack2: 'Bite',
      attBonus2: 4,
      damDiceCt2: 1,
      damDiceSize2: 6,
      damBonus2: 2
  ),
  const Beast(
      bType: 'Wolf',
      cr: '1/4',
      count: 8,
      info: 'M  AC:13  Str:1  Dex:2  Con:1  Int:-4  Wis:1  Cha:-2  R:40',
      hitDiceCt: 2,
      hitDiceSize: 8,
      hitDiceBonus: 2,
      attack1: 'Bite',
      attBonus1: 4,
      damDiceCt1: 2,
      damDiceSize1: 4,
      damBonus1: 2
  ),
  const Beast(
      bType: 'Pteranodon',
      cr: '1/4',
      count: 8,
      info: 'M  AC:13  Str:1  Dex:2  Con:0  Int:-4  Wis:-1  Cha:-3  R:10 F:60',
      hitDiceCt: 3,
      hitDiceSize: 8,
      hitDiceBonus: 0,
      attack1: 'Bite',
      attBonus1: 3,
      damDiceCt1: 2,
      damDiceSize1: 4,
      damBonus1: 1
  ),
  const Beast(
      bType: 'Velociraptor',
      cr: '1/4',
      count: 8,
      info: 'T  AC:13  Str:-2  Dex:2  Con:1  Int:-3  Wis:-1  Cha:-2  R:30',
      hitDiceCt: 3,
      hitDiceSize: 4,
      hitDiceBonus: 3,
      attack1: 'Bite',
      attBonus1: 4,
      damDiceCt1: 1,
      damDiceSize1: 6,
      damBonus1: 2,
      attack2: 'Claws',
      attBonus2: 4,
      damDiceCt2: 1,
      damDiceSize2: 4,
      damBonus2: 2
  ),
  const Beast(
    bType: 'Ape',
    cr: '1/2',
    count: 4,
    info: 'M  AC:12  Str:3  Dex:2  Con:2  Int:-2  Wis:1  Cha:-2  R:30 C:30',
    hitDiceCt: 3,
    hitDiceSize: 8,
    hitDiceBonus: 6,
    attack1: 'Fist',
    attBonus1: 5,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 3,
    attack2: 'Fist',
    attBonus2: 5,
    damDiceCt2: 1,
    damDiceSize2: 6,
    damBonus2: 3,
    attack3: 'Rock',
    attBonus3: 5,
    damDiceCt3: 1,
    damDiceSize3: 6,
    damBonus3: 3
  ),
  const Beast(
    bType: 'Black Bear',
    cr: '1/2',
    count: 4,
    info: 'M  AC:11  Str:2  Dex:0  Con:2  Int:-4  Wis:1  Cha:-2  R:40 C:30',
    hitDiceCt: 3,
    hitDiceSize: 8,
    hitDiceBonus: 6,
    attack1: 'Bite',
    attBonus1: 3,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 2,
    attack2: 'Claws',
    attBonus2: 3,
    damDiceCt2: 2,
    damDiceSize2: 4,
    damBonus2: 2
  ),
  const Beast(
    bType: 'Giant Goat',
    cr: '1/2',
    count: 4,
    info: 'L  AC:11  Str:3  Dex:0  Con:1  Int:-4  Wis:1  Cha:-2  R:40',
    hitDiceCt: 3,
    hitDiceSize: 10,
    hitDiceBonus: 3,
    attack1: 'Ram',
    attBonus1: 5,
    damDiceCt1: 2,
    damDiceSize1: 4,
    damBonus1: 3,
    attack2: 'Charge',
    attBonus2: 5,
    damDiceCt2: 4,
    damDiceSize2: 4,
    damBonus2: 3
  ),
  const Beast(
    bType: 'Giant Wasp',
    cr: '1/2',
    count: 4,
    info: 'M  AC:12  Str:0  Dex:2  Con:0  Int:-5  Wis:0  Cha:-4  R:10 F:50',
    hitDiceCt: 3,
    hitDiceSize: 8,
    hitDiceBonus: 0,
    attack1: 'Sting',
    attBonus1: 4,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 2
  ),
  const Beast(
    bType: 'Reef Shark',
    cr: '1/2',
    count: 4,
    info: 'M  AC:12  Str:2  Dex:1  Con:1  Int:-5  Wis:0  Cha:-3  S:40',
    hitDiceCt: 4,
    hitDiceSize: 8,
    hitDiceBonus: 4,
    attack1: 'Bite',
    attBonus1: 4,
    damDiceCt1: 1,
    damDiceSize1: 8,
    damBonus1: 2
  ),
  const Beast(
    bType: 'Warhorse',
    cr: '1/2',
    count: 4,
    info: 'L  AC:11  Str:4  Dex:1  Con:1  Int:-4  Wis:1  Cha:-2  R:60',
    hitDiceCt: 3,
    hitDiceSize: 10,
    hitDiceBonus: 3,
    attack1: 'Hooves',
    attBonus1: 4,
    damDiceCt1: 2,
    damDiceSize1: 6,
    damBonus1: 4,
    attack2: 'Hooves',
    attBonus2: 4,
    damDiceCt2: 2,
    damDiceSize2: 6,
    damBonus2: 4
  ),
  const Beast(
    bType: 'Brown Bear',
    cr: '1',
    count: 2,
    info: 'L  AC:11  Str:4  Dex:0  Con:3  Int:-4  Wis:1  Cha:-2  R:40 C:30',
    hitDiceCt: 4,
    hitDiceSize: 10,
    hitDiceBonus: 12,
    attack1: 'Bite',
    attBonus1: 5,
    damDiceCt1: 1,
    damDiceSize1: 8,
    damBonus1: 4,
    attack2: 'Claws',
    attBonus2: 5,
    damDiceCt2: 2,
    damDiceSize2: 6,
    damBonus2: 4
  ),
  const Beast(
    bType: 'Crag Cat',
    cr: '1',
    count: 2,
    info: 'L  AC:13  Str:3  Dex:3  Con:3  Int:-3  Wis:2  Cha:-1  R:40',
    hitDiceCt: 4,
    hitDiceSize: 10,
    hitDiceBonus: 12,
    attack1: 'Claw',
    attBonus1: 5,
    damDiceCt1: 1,
    damDiceSize1: 8,
    damBonus1: 3,
    attack2: 'Bite',
    attBonus2: 5,
    damDiceCt2: 1,
    damDiceSize2: 10,
    damBonus2: 3
  ),
  const Beast(
    bType: 'Deinonychus',
    cr: '1',
    count: 2,
    info: 'M  AC:13  Str:2  Dex:2  Con:2  Int:-3  Wis:1  Cha:-2  R:40',
    hitDiceCt: 4,
    hitDiceSize: 8,
    hitDiceBonus: 8,
    attack1: 'Claw',
    attBonus1: 4,
    damDiceCt1: 1,
    damDiceSize1: 8,
    damBonus1: 2,
    attack2: 'Claw',
    attBonus2: 4,
    damDiceCt2: 1,
    damDiceSize2: 8,
    damBonus2: 2,
    attack3: 'Bite',
    attBonus3: 4,
    damDiceCt3: 1,
    damDiceSize3: 8,
    damBonus3: 2,
    attack4: 'Bite',
    attBonus4: 4,
    damDiceCt4: 1,
    damDiceSize4: 8,
    damBonus4: 2
  ),
  const Beast(
    bType: 'Dire Wolf',
    cr: '1',
    count: 2,
    info: 'L  AC:14  Str:3  Dex:2  Con:2  Int:-4  Wis:1  Cha:-2  R:40 C:50',
    hitDiceCt: 3,
    hitDiceSize: 10,
    hitDiceBonus: 7,
    attack1: 'Bite',
    attBonus1: 5,
    damDiceCt1: 2,
    damDiceSize1: 6,
    damBonus1: 3
  ),
  const Beast(
    bType: 'Giant Eagle',
    cr: '1',
    count: 2,
    info: 'L  AC:13  Str:3  Dex:3  Con:1  Int:-1  Wis:2  Cha:0  R:10 F:80',
    hitDiceCt: 4,
    hitDiceSize: 10,
    hitDiceBonus: 4,
    attack1: 'Beak',
    attBonus1: 5,
    damDiceCt1: 1,
    damDiceSize1: 6,
    damBonus1: 3,
    attack2: 'Talons',
    attBonus2: 5,
    damDiceCt2: 2,
    damDiceSize2: 6,
    damBonus2: 3
  ),
  const Beast(
      bType: 'Giant Hyena',
      cr: '1',
      count: 2,
      info: 'L  AC:12  Str:3  Dex:2  Con:2  Int:-4  Wis:1  Cha:-2  R:50',
      hitDiceCt: 6,
      hitDiceSize: 10,
      hitDiceBonus: 12,
      attack1: 'Bite',
      attBonus1: 5,
      damDiceCt1: 2,
      damDiceSize1: 6,
      damBonus1: 3
  ),
  const Beast(
      bType: 'Giant Octopus',
      cr: '1',
      count: 2,
      info: 'L  AC:11  Str:3  Dex:1  Con:3  Int:-3  Wis:0  Cha:-3  R:10 S:60',
      hitDiceCt: 8,
      hitDiceSize: 10,
      hitDiceBonus: 8,
      attack1: 'Tentacles',
      attBonus1: 5,
      damDiceCt1: 2,
      damDiceSize1: 6,
      damBonus1: 3
  ),
  const Beast(
      bType: 'Giant Spider',
      cr: '1',
      count: 2,
      info: 'L  AC:14  Str:2  Dex:3  Con:1  Int:-4  Wis:0  Cha:-3  R:30 C:30',
      hitDiceCt: 4,
      hitDiceSize: 10,
      hitDiceBonus: 4,
      attack1: 'Bite',
      attBonus1: 5,
      damDiceCt1: 1,
      damDiceSize1: 8,
      damBonus1: 3,
  ),
  const Beast(
      bType: 'Giant Toad',
      cr: '1',
      count: 2,
      info: 'L  AC:11  Str:2  Dex:1  Con:1  Int:-4  Wis:0  Cha:-4  R:20 S:40',
      hitDiceCt: 6,
      hitDiceSize: 10,
      hitDiceBonus: 6,
      attack1: 'Bite',
      attBonus1: 4,
      damDiceCt1: 1,
      damDiceSize1: 10,
      damBonus1: 2
  ),
  const Beast(
      bType: 'Giant Vulture',
      cr: '1',
      count: 2,
      info: 'L  AC:10  Str:2  Dex:0  Con:2  Int:-2  Wis:1  Cha:-2  R:10 F:60',
      hitDiceCt: 3,
      hitDiceSize: 10,
      hitDiceBonus: 6,
      attack1: 'Beak',
      attBonus1: 4,
      damDiceCt1: 2,
      damDiceSize1: 4,
      damBonus1: 2,
      attack2: 'Talons',
      attBonus2: 4,
      damDiceCt2: 2,
      damDiceSize2: 6,
      damBonus2: 2
  ),
  const Beast(
      bType: 'Lion',
      cr: '1',
      count: 2,
      info: 'L  AC:12  Str:3  Dex:2  Con:1  Int:-4  Wis:1  Cha:-1  R:50',
      hitDiceCt: 4,
      hitDiceSize: 10,
      hitDiceBonus: 4,
      attack1: 'Claw',
      attBonus1: 5,
      damDiceCt1: 1,
      damDiceSize1: 6,
      damBonus1: 3,
      attack2: 'Bite',
      attBonus2: 5,
      damDiceCt2: 1,
      damDiceSize2: 8,
      damBonus2: 3
  ),
  const Beast(
      bType: 'Tiger',
      cr: '1',
      count: 2,
      info: 'L  AC:12  Str:3  Dex:2  Con:2  Int:-4  Wis:1  Cha:-1  R:40',
      hitDiceCt: 5,
      hitDiceSize: 10,
      hitDiceBonus: 10,
      attack1: 'Claw',
      attBonus1: 5,
      damDiceCt1: 1,
      damDiceSize1: 8,
      damBonus1: 3,
      attack2: 'Bite',
      attBonus2: 5,
      damDiceCt2: 1,
      damDiceSize2: 10,
      damBonus2: 3
  ),
  const Beast(
      bType: 'Allosaurus',
      cr: '2',
      count: 1,
      info: 'L  AC:13  Str:4  Dex:1  Con:3  Int:-4  Wis:1  Cha:-3  R:60',
      hitDiceCt: 6,
      hitDiceSize: 10,
      hitDiceBonus: 18,
      attack1: 'Claw',
      attBonus1: 6,
      damDiceCt1: 1,
      damDiceSize1: 8,
      damBonus1: 4,
      attack2: 'Bite',
      attBonus2: 6,
      damDiceCt2: 2,
      damDiceSize2: 10,
      damBonus2: 4
  ),
  const Beast(
      bType: 'Polar Bear',
      cr: '2',
      count: 1,
      info: 'L  AC:12  Str:5  Dex:0  Con:3  Int:-4  Wis:1  Cha:-2  R:40 S:30',
      hitDiceCt: 5,
      hitDiceSize: 10,
      hitDiceBonus: 15,
      attack1: 'Claws',
      attBonus1: 7,
      damDiceCt1: 2,
      damDiceSize1: 6,
      damBonus1: 5,
      attack2: 'Bite',
      attBonus2: 7,
      damDiceCt2: 1,
      damDiceSize2: 8,
      damBonus2: 5
  ),
  const Beast(
      bType: 'Saber-Toothed Tiger',
      cr: '2',
      count: 1,
      info: 'L  AC:12  Str:4  Dex:2  Con:2  Int:-4  Wis:1  Cha:-1  R:40',
      hitDiceCt: 7,
      hitDiceSize: 10,
      hitDiceBonus: 14,
      attack1: 'Claw',
      attBonus1: 6,
      damDiceCt1: 2,
      damDiceSize1: 6,
      damBonus1: 5,
      attack2: 'Bite',
      attBonus2: 6,
      damDiceCt2: 1,
      damDiceSize2: 10,
      damBonus2: 5
  ),
  const Beast(
      bType: 'Giant Constrictor Snake',
      cr: '2',
      count: 1,
      info: 'H  AC:12  Str:4  Dex:2  Con:1  Int:-5  Wis:0  Cha:-4  R:40 S:30',
      hitDiceCt: 8,
      hitDiceSize: 12,
      hitDiceBonus: 8,
      attack1: 'Bite',
      attBonus1: 6,
      damDiceCt1: 2,
      damDiceSize1: 6,
      damBonus1: 4,
      attack2: 'Constrict',
      attBonus2: 6,
      damDiceCt2: 2,
      damDiceSize2: 8,
      damBonus2: 4
  ),
  const Beast(
      bType: 'Giant Elk',
      cr: '2',
      count: 1,
      info: 'H  AC:14  Str:4  Dex:3  Con:2  Int:-2  Wis:2  Cha:0  R:60',
      hitDiceCt: 5,
      hitDiceSize: 12,
      hitDiceBonus: 10,
      attack1: 'Ram',
      attBonus1: 6,
      damDiceCt1: 2,
      damDiceSize1: 6,
      damBonus1: 4,
      attack2: 'Hooves',
      attBonus2: 6,
      damDiceCt2: 4,
      damDiceSize2: 8,
      damBonus2: 4
  ),
  const Beast(
      bType: 'Hunter Shark',
      cr: '2',
      count: 1,
      info: 'L  AC:12  Str:4  Dex:1  Con:2  Int:-5  Wis:0  Cha:-3  S:40',
      hitDiceCt: 6,
      hitDiceSize: 10,
      hitDiceBonus: 12,
      attack1: 'Bite',
      attBonus1: 6,
      damDiceCt1: 2,
      damDiceSize1: 8,
      damBonus1: 4
  ),
  const Beast(
      bType: 'Plesiosaurus',
      cr: '2',
      count: 1,
      info: 'L  AC:13  Str:4  Dex:2  Con:3  Int:-4  Wis:1  Cha:-3  R:20 S:40',
      hitDiceCt: 8,
      hitDiceSize: 10,
      hitDiceBonus: 24,
      attack1: 'Bite',
      attBonus1: 6,
      damDiceCt1: 3,
      damDiceSize1: 6,
      damBonus1: 4
  ),
  const Beast(
      bType: 'Quetzalcoatlus',
      cr: '2',
      count: 1,
      info: 'H  AC:13  Str:2  Dex:1  Con:1  Int:-4  Wis:0  Cha:-3  R:10 F:80',
      hitDiceCt: 4,
      hitDiceSize: 12,
      hitDiceBonus: 4,
      attack1: 'Bite',
      attBonus1: 4,
      damDiceCt1: 3,
      damDiceSize1: 6,
      damBonus1: 2,
      attack2: 'Dive',
      attBonus2: 4,
      damDiceCt2: 6,
      damDiceSize2: 6,
      damBonus2: 2
  ),
  const Beast(
      bType: 'Rhinoceros',
      cr: '2',
      count: 1,
      info: 'L  AC:11  Str:5  Dex:-1  Con:2  Int:-4  Wis:1  Cha:-2  R:40',
      hitDiceCt: 6,
      hitDiceSize: 10,
      hitDiceBonus: 12,
      attack1: 'Gore',
      attBonus1: 7,
      damDiceCt1: 2,
      damDiceSize1: 8,
      damBonus1: 5,
      attack2: 'Charge',
      attBonus2: 7,
      damDiceCt2: 4,
      damDiceSize2: 8,
      damBonus2: 5
  ),
];